<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Clientes extends Model
{
    use HasFactory;

    protected $table = 'clientes';

    protected $fillable = ['CLIE_CLIENTE', 'CLIE_NOMBRE', 'CLIE_NOMBRE_LEGAL', 
    'CLIE_ES_CLI_GLOB', 'CLIE_DOMICILIO', 'CLIE_LOCALIDAD', 'CLIE_COD_POSTAL', 
    'CLIE_PROVINCIA', 'CLIE_PAIS', 'CLIE_TELEFONO', 'CLIE_FAX', 'CLIE_EMAIL', 
    'CLIE_OBSERVACION', 'CLIE_COD_PROVEEDOR', 'CLIE_REFERENCIA', 'CLIE_HORA_ATENCION', 
    'CLIE_HORA_ENTREGA', 'CLIE_CONDICION_IVA', 'CLIE_CUIT', 'CLIE_ING_BRUTOS', 
    'CLIE_CONTAC_VENTA', 'CLIE_CONTAC_COBRO', 'CLIE_COND_PAGO', 'CLIE_MONEDA_CTE', 
    'CLIE_CUENTA_CLIE', 'CLIE_TIPO_CLI', 'CLIE_ACTIVIDAD_CLI', 'CLIE_CLASIF_1', 
    'CLIE_CLASIF_2', 'CLIE_CLASIF_3', 'CLIE_CLASIF_4', 'CLIE_VENDEDOR', 'CLIE_ZONA_VENTA', 
    'CLIE_COBRADOR', 'CLIE_FLETE', 'CLIE_BLOQUEADO_PED', 'CLIE_BLOQUEADO_FAC', 
    'CLIE_FECHA_ALTA', 'CLIE_FECHA_BAJA', 'CLIE_HABIL_WEB', 'CLIE_PASSWORD_WEB', 
    'CLIE_FORMATO_FIMC', 'CLIE_HABIL_FABN', 'CLIE_VENDEDOR_2', 'CLIE_STRING_1', 
    'CLIE_STRING_2', 'CLIE_STRING_3', 'CLIE_STRING_4', 'CLIE_FECHA_1', 'CLIE_FECHA_2', 
    'CLIE_FECHA_3', 'CLIE_FECHA_4', 'CLIE_CLASIF_NPCV_1', 'CLIE_CLASIF_NPCV_2', 
    'CLIE_CLASIF_NPCV_3', 'CLIE_CLASIF_NPCV_4', 'CLIE_CLASIF_NPCV_5', 'CLIE_CLASIF_NPCV_6', 
    'CLIE_HABIL_CC_CLIE', 'CLIE_CLIENTE_EXT', 'CLIE_FECHA_PROX_GC', 'CLIE_PROX_GES_COBR', 
    'CLIE_ACCT_GENCBPTE', 'CLIE_NODO_ORIGEN', 'CLIE_MUNICIPIO', 'CLIE_INF_TABASTO', 
    'CLIE_COBRO_CORREL', 'CLIE_VEHICULO', 'CLIE_DISTRIBUIDOR', 'CLIE_ZONA_DISTRIB'
    ];
}
